
var arrTextFiles ={ 
"01-01-01":"pic 01 00newline,bub 0newline,txt \"Ha ha, yes. Rather an easy one, even for you my humble student.\"newline,txt \"Every row and column required that 5 marks be made.\"newline,pic 00 01newline,txt \"No problem!\"newline,pic 01 01newline,txt \"But it does illustrate a most important point: every glyph has an element of certainty.\"newline,txt \"Always look for that certainty and you will have found your place to begin!\"newline,txt \"Now let\'s see how you fare with the next!...\"",

"01-01-02":"pic 00 15newline,bub 0newline,txt \"I\'ve done it!\"newline,pic 01 01newline,txt \"Good, good. Start with certainty, in this case a full row of marks, and the rest of the solution soon falls into place, what?\"newline,pic 01 00newline,txt \"Like Ogbeard\'s cloak, start pulling at a single thread and before long all is unravelled!\"newline,pic 00 07newline,txt \"So, the clue numbers show groups of marks I have to make.\"newline,txt \"By looking at the clues along the top and the bottom I can work out exactly where they must go, so I can break the spell!\"newline,pic 00 01newline,txt \"I actually hope the next one is a little more taxing.\"",

"01-01-03":"pic 01 01newline,bub 0newline,txt \"Very good. Now - do you see the diamond?\"newline,pic 00 06newline,txt \"Hmm? Diamond?\"newline,pic 01 01newline,txt \"The empty space in the centre of that puzzle!\"newline,txt \"Often what isn\'t there, is as important as what is. That\'s what helps you figure out the whole picture, my lad.\"newline,txt \"A good Glyphix Master always *blanks* out the squares he knows are empty! (Right-click them with the mouse)\"newline,txt \"I didn\'t get to where I am today by not Right-clicking my blanks!\"newline,pic 00 05newline,bub 1newline,txt \"Uhhh... \"Right-clicking\"...okay.\"newline,pic 01 01newline,txt \"Oh, did I say that out loud?\"newline,txt \"Well it\'s good advice. Onto the next conundrum!\"",

"01-01-04":"pic 00 01newline,bub 0newline,txt \"Yeah!\"newline,pic 01 01newline,txt \"Ah you\'ve solved my sun puzzle. You\'re coming along nicely!\"newline,txt \"And may it serve as a reminder - once you\'re out in the big, wide world the solutions will resemble the actual things that are trapped inside the glyphs.\"newline,pic 01 02newline,txt \"Not the sun itself, of course. There was never a Pox Gremlin big enough to pull that off, thank goodness.\"newline,pic 00 06newline,txt \"Pox Gremlin?...\"newline,pic 01 01newline,txt \"All in good time, my boy.\"",

"01-01-05":"pic 01 01newline,bub 0newline,txt \"Aha! Know the face of your enemy!\"newline,pic 01 02newline,txt \"Awkward, squirmy little ruffians they are. Brrr! I came up against my fair share of them, I can tell you.\"newline,pic 00 09newline,bub 1newline,txt \"So there really is something... loose out there... turning things into glyphs?!\"newline,pic 01 02newline,bub 0newline,txt \"Prized possessions, livestock, even people can be turned into glyphs! The Gremlins were the scourge of wizard-kind!\"newline,pic 01 01newline,txt \"You should really turn to some of my later chapters and relive my famous exploits... quite outstanding.\"newline,pic 00 01newline,txt \"Um yes. I don\'t think there\'s time! Sorry.\"newline,",

"01-01-06":"pic 00 01newline,bub 0newline,txt \"I\'m definitely getting the hang of these.\"newline,pic 01 01newline,txt \"Ah yes, these dry runs are all well and good, but it is the practical test of your skills that will really separate the wizard from the wannabees.\"newline,pic 01 02newline,txt \"Out there, in the mean streets, evil forests and spine-chilling mountains of the real world a Glyphix Master needs courage and perseverance to survive!\"newline,pic 01 00newline,txt \"Heroism!\"newline,pic 01 01newline,txt \"That\'s what it demands, nothing more and nothing less!\"newline,bub 1newline,txt \"(Although a spare pair of underpants is always a blessing)\"newline,pic 00 04newline,bub 0newline,txt \"*Gulp*\"newline,newline,",

"01-01-07":"pic 01 01newline,bub 0newline,txt \"Heroism and courage have their reward$!  Lucrative book deals for example.\"newline,pic 01 00newline,txt \"It is, how they say, all about the benjamins, bay-bee. *ahem* But I digress...\".newline,pic 00 13newline,bub 1newline,txt \"I\'m sure that old coot was a few runes short of a spell.\"newline,pic 01 02newline,bub 2newline,txt \"Show some RESPECT, small-fry. Or I\'ll turn my pages blank!\"newline,pic 00 09newline,bub 1newline,txt \"Aieee!\"newline,pic 00 05newline,txt \"Never talk back to a magic book, Skimlet.\"newline,newline,",

"01-01-08":"pic 01 01newline,bub 0newline,txt \"Very good, I\'m sure that one caused you no difficulties.\"newline,pic 00 06newline,txt \"Is this test - an hourglass?\"newline,pic 01 01newline,txt \"The hourglass. A -critical- wizarding tool if you want to solve even the simplest of glyphs.\"newline,txt \"Every glyph has a natural time limit in which its spell can be unwoven, you see.\"newline,txt \"This fellow will help you keep track of how exactly long you have to make your attempt!\"newline,pic 00 05newline,txt \"And if I fail?!\"newline,bub 0newline,pic 01 02newline,txt \"Oh, you can always have another stab at it I suppose. Not that I ever needed to.\"newline,txt \"The trick is to make sure you don\'t place any marks incorrectly, that weakens your counter-magic and...\"newline,pic 00 01newline,txt \"Causes a time penalty!\"newline,pic 01 01newline,txt \"Got it in one, my boy. You\'re a fast learner at least, if a bit wet behind the ears.\"newline,pic 00 03newline,bub 1newline,txt \"...Heheh...\"newline,pic 01 01newline,bub 0newline,txt \"Real glyphs are much bigger and have more elaborate, detailed solutions! Always keep one eye on your hourglass.\"",

"01-01-09":"pic 01 01newline,bub 0newline,txt \"Well solved, this particular test puzzle represents the *magic eye*...\"newline,txt \"Every good wizard keeps a few extra tricks up his sleeve, you never know when you\'re going to find yourself in a tight spot.\"newline,pic 01 03newline,txt \"Oh, I remember one particular time I was out in the hinterlands of Bolsogovia. A dozen armed guards came storming in on myself and the Sultan\'s wife.\"newline,txt \"Of course there was a quite innocent explanation -\"newline,pic 00 02newline,txt \"I really am in a hurry, Sir Methusaleh...\"newline,pic 01 03newline,txt \"....\"newline,pic 00 08newline,bub 2newline,txt \"*AHEM*\"newline,pic 01 02newline,bub 0newline,txt \"Hmm? Ah, yes we must stick to the matter at hand.\"newline,pic 01 01newline,txt \"As I was saying... when you find yourself on a particularly tough puzzle you may choose to speed things along.\"newline,txt \"Call on the magic eye of the Reveal Spell and it will uncover some of the solution for you!\"newline,pic 00 27newline,txt \"A Reveal Spell? That sounds very useful.\"newline,pic 01 01newline,txt \"Quite so. Although its power is finite and must be used sparingly. Pity.\"",

"01-01-10":"pic 00 06newline,bub 0newline,txt \"A little boat?\"newline,pic 01 01newline,txt \"There is a Journey ahead for he or she who undertakes the art of Glyph-solving. Perhaps a great Journey, indeed.\"newline,pic 01 01newline,txt \"For me it was a Journey that blazed around the entire world.\"newline,bub 2newline,txt \"A Journey that took me from the very depths of despair to the heights of fame and fortune, and everything in between!\"newline,pic 01 01newline,bub 0newline,txt \"Ah, but that is simply history now. Who can say where yours will take you?\"newline,pic 00 05newline,txt \"I\'m not really looking for anything that e-exciting, to be honest!\"newline,pic 01 01newline,txt \"Nonsense!\"newline,txt \"All you need to remember are the following rules and ye shall be fine!:\"newline,txt \"Good boots are your best friends. Sleep little and often. Don\'t drink the water...\"newline,txt \"Pack a spare hat. And, uhh, \'tis an ill wind that bears no moss.\"newline,pic 01 03newline,bub 1newline,txt \"Oh wait ... \'tis an ill wind that... something something... look out for bears and don\'t eat the moss?\"newline,pic 00 06newline,bub 0newline,txt \"Um?\"newline,pic 01 01newline,txt \"Well the important thing is... there\'s a fantastic path ahead of you,\"newline,txt \"And I\'m quite certainly, almost positive that you are well up to the task, I suspect. Stranger things have happened.\"newline,pic 01 03newline,txt \"(mumble)\"newline,pic 00 05newline,txt \"...\"",

"01-02-01":"pic 00 12newline,bub 0newline,txt \"*Gasp* There, I\'ve solved it!\"newline,pic 01 08newline,txt \"Indeed you have, my boy. I was never in any doubt.\"newline,",

"02-01-01":"pic 00 09newline,bub 0newline,txt \"Something\'s happening!\"newline,pic 00 14newline,bub 2newline,txt \"Whoa!\"newline,pic 03 02newline,txt \"Me anvil!\"newline,pic 00 15newline,bub 0newline,txt \"Hey, Methusaleh\'s wand really does work!\"newline,pic 03 01newline,txt \"Hrm, it looks a\'right. This old beauty was made to last the ages.\"newline,txt \"Fine, ye can fix the rest o\' me stuff too - what\'s yer name?\"newline,pic 00 15newline,txt \"Skimlet. And I\'ll fix \'em, no problem!\"newline,pic 03 01newline,txt \"A\'right don\'t get cocky, Niblet!\"",

"02-01-02":"pic 00 12newline,bub 0newline,txt \"Blackthumb\'s hammer, I\'ve freed it from the glyph!\"newline,pic 00 16newline,txt \"Phew, it weighs more than me!\"newline,pic 03 01newline,txt \"Ah, me small hammer. Now I can stick it back in me tool belt where it belongs. (pat pat)\"",

"02-01-03":"pic 00 17newline,bub 0newline,txt \"I think I found your - lunch?!\"newline,pic 03 02newline,txt \"Mmm-mm, pickled mutton bap.\"newline,txt \"Only Mrs Blackthumb knows how to keep the lard so crispy.\"newline,pic 00 08newline,txt \"(Gulp) - You\'re a lucky man.\"",

"02-01-04":"pic 00 01newline,bub 0newline,txt \"One iron horseshoe, back to normal!\"newline,pic 03 01newline,txt \"No-one in a hundred leagues of here makes them any finer. Mebee, no-one in the whole of Magus Magna.\"newline,pic 00 15newline,txt \"...\"newline,pic 03 00newline,bub 2newline,txt \"AND IT AIN\'T DONE WITH NO MAGICAL FUNNY BUSINESS, NEITHER!\"newline,pic 03 01newline,bub 0newline,txt \"Only things a real man can rely on in this world are elbow grease and hard graft!\"newline,pic 00 05newline,txt \"Heheh!\"",

"02-01-05":"pic 00 01newline,bub 0newline,txt \"There, it\'s Blackthumb\'s water bucket. I really am getting the hang of this wand.\"newline,pic 00 02newline,txt \"That gremlin doesn\'t stand a chance! ... right?\"",

"02-01-06":"pic 03 02newline,bub 0newline,txt \"Me tongs. Me lovely tongs, back where they belong.\"newline,pic 03 01newline,txt \"A man don\'t feel right if he don\'t know where his tongs are.\" ",

"02-01-07":"pic 00 18newline,bub 1newline,txt \"Oops! Sharp!\"newline,pic 00 01newline,bub 0newline,txt \"Here\'s your sword, sir.\"newline,pic 03 01newline,txt \"Careful with that, pup. You don\'t look old enough to be handling weaponry, or to be swinging that wand about fer that matter!\"newline,pic 00 01newline,txt \"I assure you, I\'m - (ahem) - fully qualified for the job.\"newline,pic 00 06newline,bub 3newline,txt \"If being the only available wizard within three leagues of here makes me qualified, that is.\"",

"02-01-08":"pic 03 01newline,bub 0newline,txt \"That\'s one o\' me finest heraldry shields. There better not be a scratch on it.\"newline,pic 00 15newline,txt \"-Yes-, chalk up another victory for the wizard in the baggy blue robes!\"newline,pic 00 02newline,txt \"I knew I could do this!\"",

"02-01-09":"pic 00 19newline,bub 1newline,txt \"Ack!... still ...warm.\"newline,pic 03 02newline,bub 0newline,txt \"Ahhh, me cacks. I left em hanging over the forge, keeping toasty.\"newline,pic 00 17newline,bub 1newline,txt \"H-here you are...\"",

"02-02-01":"pic 00 18newline,bub 2newline,txt \"Oh my...(gasp!)\"newline,bub 0newline,txt \"The gremlin took a bite right out of this apple before glyphing it!\"",

"02-02-02":"pic 00 01newline,bub 0newline,txt \"Thick wooly socks.\"newline,pic 00 06newline,bub 3newline,txt \"Maybe I should leave a couple of coins and keep these... I wonder how far North the journey will take me?\"newline,pic 00 01newline,txt \"Ha! I\'m probably being silly.\"",

"02-02-03":"pic 00 07newline,bub 0newline,txt \"Mushrooms from Nether Weir! They would have been sitting... there on Wanderer Murdo\'s stall when the gremlin showed up.\"newline,pic 00 13newline,txt \"They\'re a rare delicacy here in Thaumhaven, although a bit too spicy for most tastes.\"newline,txt \"I accidentally used some of these in a mushroom omelette I made for Howard last year.\"newline,pic 00 03newline,bub 1newline,txt \"...Once he\'d climbed back out of the nearest pond, he wasn\'t best pleased.\"",

"02-02-04":"pic 00 06newline,bub 0newline,txt \"A silver necklace and locket, it\'s very striking. It\'d be a gift fit for Kara...\"newline,pic 00 21newline,txt \"Ahhh, Princess Kara!\"newline,pic 00 22newline,txt \"Will you ever know that I exist?\"newline,pic 00 03newline,txt \"...I think I\'ll just tuck it back onto the Jeweller\'s stall.\"",

"02-02-05":"pic 00 06newline,bub 0newline,txt \"Hey kitty, are you okay?\"newline,pic 00 01newline,txt \"Wow, off he goes. He\'s not hurt at all!\"",

"02-02-06":"pic 00 18newline,bub 0newline,txt \"It\'s a large fruit pie - with footprints in it!\"newline,pic 00 20newline,txt \"That thing is a menace!\"",

"02-02-07":"pic 00 17newline,bub 0newline,txt \"Errrgh! That\'s... I hope no one saw me solve that one.\"newline,pic 00 23newline,bub 1newline,txt \"The creature is toying with me and I\'m -not- going to stand for it!\"",

"02-02-08":"pic 00 01newline,bub 0newline,txt \"Whoo! That took some solving, and now I can see why... it\'s the Town Square\'s statue of Methusaleh.\"newline,pic 00 07newline,txt \"I can just make out the weathered inscription...\" newline,txt \"\'Constructed to commemorate the achievements of the Great Wizard Oban Methusaleh, who did rid the world of a terrible magical menace.\'\"newline,txt \"\'Ne\'er shall the Pox Gremlins threaten Thaumhaven\'s fine streets and spires again.\'\"newline,pic 00 01newline,txt \"It\'s funny, but I\'d never paid this old thing much attention before. It\'s been here so many centuries that it just became part of the scenery.\"newline,pic 00 00newline,txt \"Wow, so Methusaleh really did rid the world of the gremlins with this very wand!\"newline,pic 00 06newline,txt \"But then where did this new gremlin come from? And why is it here?\"",

"02-03-01":"pic 00 12newline,bub 0newline,txt \"Yes! The glyph is beaten and -\"",

"02-05-01":"pic 00 01newline,bub 0newline,txt \"It\'s a grimy tankard of something dark and frothy, that smells like creosote.\"newline,pic 03 04newline,txt \"The Axe and Stump\'s best grog. Help yourself, it\'ll lubricate your brain muscles!\"newline,pic 00 01newline,txt \"Actually, I think I\'m a bit, er - young, thanks.\"",

"02-05-02":"pic 00 15newline,bub 0newline,txt \"One bar stool, good as new.\"newline,pic 00 01newline,txt \"Well, as good as before.\"",

"02-05-03":"pic 00 17newline,bub 0newline,txt \"Argh, I think I\'ve found someone or something\'s tooth!\"newline,pic 03 04newline,txt \"Just chuck it back on the floor, guv. I haven\'t swept up after last nights brawl.\"newline,pic 00 08newline,txt \"(shudder)\"",

"02-05-04":"pic 00 17newline,bub 0newline,txt \"Phew, these multi-part glyphs take a while, but it\'s satisfying to beat them.\"newline,pic 03 04newline,bub 2newline,txt \"\'Ey! Glory be, you\'ve rescued my Grog barrel. Now I can serve again!\"",

"02-05-05":"pic 00 06newline,bub 0newline,txt \"Here you are. I think it\'s a glass of... paint stripper?\"newline,pic 03 04newline,txt \"Rose-ay Grog ...for the ladies.\"",

"02-05-06":"pic 00 06newline,bub 0newline,txt \"What the-?\"newline,pic 03 04newline,txt \"Quite the conversation piece, ain\'t he squire? Lovingly stuffed and mounted.\"newline,pic 03 06newline,txt \"(sigh) It\'s a sad reminder of my Berserker days though. If it weren\'t for the unfortunate accident I\'d never have retired...\"newline,pic 00 06newline,txt \"Um, \'accident\'?\"newline,pic 03 06newline,txt \"How was I supposed to know swamp trolls had become a protected species?!\"newline,pic 03 05newline,bub 2newline,txt \"It\'s blummin\' political correctness gone mad!\"newline,pic 00 05newline,bub 0newline,txt \"... yes, that -is-... very \'unfortunate\'.\" ",

"02-05-07":"pic 00 01newline,bub 0newline,txt \"Hmm, a deadly weapon of some kind?\"newline,pic 03 04newline,txt \"My trusty peacekeeper.\"newline,pic 03 05newline,txt \"A quick THWOMP over the head calms the most rowdy of customer. Works a treat.\"",

"02-05-08":"pic 03 04newline,bub 0newline,txt \"Oh smashin\', pass it over ...the Stump wouldn\'t be a proper tavern without its darts board.\"newline,txt \"It\'s the most important thing, you know, after the Grog, the Grog-nuts and the concealed weaponry!\"newline,pic 00 06newline,txt \"I\'ve never seen one before - It\'s some kind of sporting game of skill?\"newline,pic 03 04newline,txt \"Oh yeah, that\'s the idea. A true gentleman\'s game.\"newline,txt \"Although to tell the truth it leads to more bloody arguments than anyfing else around here...\"newline,txt \"Still, tradition\'s tradition. Decapitations or not.\"newline,pic 00 01newline,txt \"I\'m, er... I\'m learning a lot from you.\"newline,",

"02-06-01":"pic 00 07newline,bub 0newline,txt \"That\'s odd. The wand had to create a bigger grid to help me beat that one. Tougher!\"newline,pic 00 18newline,bub 1newline,txt \"I wonder how big glyphs can get?!\"newline,pic 00 15newline,bub 0newline,txt \"Still, it was no match for me. Here you are Artemis!\"newline,pic 04 02newline,txt \"My magic hoe! I had this specially enchanted for easy field work.\"newline,pic 00 01newline,txt \"Very, er - practical.\"newline,pic 04 00newline,txt \"Exactly! You\'ve got it in one!\"newline,txt \"Magical studies are advancing at a fantastic rate and enriching the lives of those brave enough to apply them!\"newline,pic 04 01newline,txt \"Oh, some may look on pioneers like myself as eccentrics - but the rewards of this, science!, are limitless!\"newline,pic 04 03newline,bub 2newline,txt \"Mwa-ha-haa-HA-HAA!\"newline,pic 00 18newline,bub 0newline,txt \"Eep!\"newline,pic 04 00newline,txt \"Sorry, I -can- get a bit enthusiastic. It\'s just all so exciting!\"",

"02-06-02":"pic 00 18newline,bub 0newline,txt \"Oh my ... That\'s a... what the heck is that?!\"newline,pic 04 02newline,txt \"This is a Squppig, my good wizard!\"newline,pic 00 01newline,txt \"Square... pigs...\"newline,pic 04 00newline,txt \"This particular fellow is Cubert. Plucky little devil -\"newline,txt \"- And very convenient for meat loaf one day!\" ",

"02-06-03":"pic 00 01newline,bub 0newline,txt \"A large sack of grain.\"newline,pic 04 00newline,txt \"Yes indeed. -Thaumic- grain, full of wizardly goodness.\"newline,txt \"I couldn\'t have raised my Quadruphens without.\"newline,pic 00 18newline,txt \"You have four-legged chickens?\"newline,pic 04 00newline,txt \"Well, not anymore. I\'ll need to look into building taller fences before I try that again.\"",

"02-06-04":"pic 00 06newline,bub 0newline,txt \"Uh, Artemis? I\'m sorry - I think something went horribly wrong with this one!\"newline,pic 04 02newline,txt \"Ha! No, no, no. This is a new strain of Gigantic \'Neep!\"newline,txt \"I\'m no wizard, but I\'m proud to say it\'s the fruit of my -own- modest experiments.\"newline,pic 00 09newline,bub 2newline,txt \"Monster turnips! T-this isn\'t right, Artemis!\"newline,pic 04 00newline,bub 0newline,txt \"Yes, I am having trouble convincing my customers to eat vegetables with faces. Sad, really.\"",

"02-06-05":"pic 04 00newline,bub 0newline,txt \"Aha, another original wonder of Groat Farm\'s magical, animal husbandry.\"newline,pic 00 15newline,txt \"A gingham sheep? Well, I guess that -is- pretty impressive.\"newline,pic 04 00newline,txt \"Now I just need to figure out how to grow much, much flatter versions. Instant tablecloths!\"newline,pic 04 01newline,bub 1newline,txt \"Hmm, perhaps some flat fish and a good morphic spell would do the trick?\"newline,pic 00 05newline,bub 0newline,txt \"...\"",

"02-06-06":"pic 00 01newline,bub 0newline,txt \"Mmm, that smells good!\"newline,pic 04 00newline,txt \"Nothing beats farm-fresh food! Here, take some of these hot pasties with you.\"newline,pic 00 15newline,txt \"If you insist!\"newline,pic 04 01newline,txt \"Made from Squppig, Monster Neep and Gingham Sheep! I\'m sure you\'ll find it an eye-opening experience!\"newline,pic 04 00newline,txt \"Oh dear. Something gone down the wrong way, has it?\"newline,pic 00 08newline,bub 1newline,txt \"(Hack hack!)\"",

"02-07-01":"pic 00 01newline,bub 0newline,txt \"It\'s Howard\'s staff, the focus of his Earth magic.\"newline,pic 00 25newline,txt \"He wouldn\'t leave this unattended, any more than I\'d leave my Water hat lying around.\"",

"02-07-02":"pic 00 18newline,bub 0newline,txt \"His pipe... still lit! This isn\'t good.\"newline,pic 00 25newline,txt \"Come on Skimlet, hurry!\"",

"02-07-03":"pic 00 01newline,bub 0newline,txt \"Look at this, it\'s a book about Pox Gremlins! Howard must have been anticipating something.\"newline,pic 00 07newline,txt \"It\'s lying open on this page:\"newline,pic 01 11newline,txt \"\'For a brief period, 500 years ago, wizards took to using a most unusual accessory.\'\"newline,txt \"\'Many gave up their typical familiars, in favor of a type of gremlin with powers of transformation.\'\"newline,txt \"\'These Pox Gremlins were able to turn the most cumbersome of items into handy, pocket sized tablets of stone.\'\"newline,txt \"\'And so, word of their usefulness and their popularity spread across the lands like wildfire.\'\"newline,bub 1newline,txt \"\'Unfortunately, ... th ... lins were uncont...\'\"newline,pic 00 18newline,bub 0newline,txt \"Oh, the rest has been crudely ripped out. Shredded by tiny claws!\"newline,pic 00 04newline,txt \"(Gulp)\" ",

"02-07-04":"pic 00 09newline,bub 0newline,txt \"Cripes! Howard\'s owl was trapped in that glyph!\"newline,pic 00 15newline,txt \"Hey... you\'re fine, aren\'t you Scrye? There\'s not a feather out of place.\"newline,pic 00 01newline,txt \"He looks totally unfazed, patiently waiting for his master\'s return...\"newline,pic 00 25newline,txt \"Where is he Scrye? What\'s happened?\"",

"02-07-05":"pic 00 12newline,bub 0newline,txt \"Master!!!...\"newline,pic 02 00newline,txt \"Haha, quite so! Though you musn\'t call me that any more, my old apprentice.\"newline,pic 00 01newline,txt \"You\'ve proven yourself far beyond your days of study, especially today it seems!\"newline,pic 00 15newline,bub 2newline,txt \"You\'re safe!\"newline,pic 02 02newline,bub 0newline,txt \"Mrrk! It tastes like I\'ve had a mouthful of gravel - but aside from that...\"newline,pic 02 05newline,txt \"...Yes, I am myself again.\""


};
	